### ISSUE TITLE
[BUG] when trying for the first time

### ISSUE THREAD

**Issue by a989898** [Svinokur/selenium_driver_updater#5]
Error when trying the get started code.

2023-12-19 08:02:29,059 INFO Your selenium-driver-updater library is up to date.
2023-12-19 08:02:32,419 INFO Current version of chromedriver: 120.0.6099.109
2023-12-19 08:02:33,762 INFO Latest version of chromedriver: 120.0.6099.109
2023-12-19 08:02:33,762 INFO Your existing chromedriver is up to date. current_version: 120.0.6099.109 latest_version: 120.0.6099.109
Traceback (most recent call last):
  File "C:\Users\Engineer\AppData\Local\Programs\Python\Python312\Lib\site-packages\selenium\webdriver\common\driver_finder.py", line 38, in get_path
    path = SeleniumManager().driver_location(options) if path is None else path
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Engineer\AppData\Local\Programs\Python\Python312\Lib\site-packages\selenium\webdriver\common\selenium_manager.py", line 84, in driver_location
    browser = options.capabilities["browserName"]
              ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'capabilities'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Engineer\register-chrome-driver-path.py", line 9, in <module>
    driver = webdriver.Chrome(filename)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Engineer\AppData\Local\Programs\Python\Python312\Lib\site-packages\selenium\webdriver\chrome\webdriver.py", line 45, in __init__
    super().__init__(
  File "C:\Users\Engineer\AppData\Local\Programs\Python\Python312\Lib\site-packages\selenium\webdriver\chromium\webdriver.py", line 49, in __init__
    self.service.path = DriverFinder.get_path(self.service, options)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Engineer\AppData\Local\Programs\Python\Python312\Lib\site-packages\selenium\webdriver\common\driver_finder.py", line 40, in get_path
    msg = f"Unable to obtain driver for {options.capabilities['browserName']} using Selenium Manager."
                                         ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'capabilities'

 - OS: Windows10
 - Driver chromedriver

**Comment by Svinokur** [comment]
Hello, thanks for the issue, but it seems that this error is in SeleniumManager, not in selenium_driver_updater
